---

- name: Ensure pipx packages are installed from GitHub repositories
  command:
    cmd: "pipx install --force git+{{ item.url }}#egg={{ item.name }}"
  loop:
    - { name: 'impacket', url: 'https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'https://github.com/Porchetta-Industries/CrackMapExec.git' }



