---
# - name: "Updating Firefox Policies"
#   template: 
#     src: "templates/policies.json.j2"
#     dest: "/usr/share/firefox-esr/distribution/policies.json"
#   become: true
#   become_method: sudo

- name: Ensure Firefox is installed
  apt:
    name: firefox
    state: present
  become: true
  become_method: sudo
# Assuming you've already fetched the necessary extensions in .xpi format and placed them somewhere accessible.
# Here, I'm just giving a generic path. Adjust as necessary.
- name: Fetch extensions
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/latest/{{ item }}/latest.xpi"
    dest: "/tmp/{{ item }}.xpi"
  loop: "{{ FirefoxPlugins }}"

# Create Firefox profiles. Adjust the command to properly create profiles as you need them.
- name: Create Firefox profiles
  command: "firefox -CreateProfile {{ item }}"
  loop:
    - low_user1
    - low_user2
    - high_user1
    - high_user2

- name: Copy get_profile_dir.py to target
  copy:
    src: "files/get_profile_dir.py"
    dest: "/tmp/get_profile_dir.py"
    mode: '0755'

- name: Get Firefox profile directory for each profile
  command:
    cmd: "python3 /tmp/get_profile_dir.py {{ item }}"
  register: profiles_directory
  with_items: "{{ firefox_profiles }}"
  loop_control:
    loop_var: profile_name

- name: Copy extensions to Firefox profile
  copy:
    src: "/tmp/{{ item.name }}.xpi"
    dest: "{{ profile_dir.stdout }}/extensions/{{ item.name }}.xpi"
  with_nested:
    - "{{ profiles_directory.results }}"
    - "{{ FirefoxPlugins }}"
  loop_control:
    loop_var: profile_dir


