---
- name: Ensure Firefox is installed
  apt:
    name: firefox
    state: present
  become: true
  become_method: sudo

- name: Fetch extensions
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/latest/{{ item }}/latest.xpi"
    dest: "/tmp/{{ item }}.xpi"
  loop: "{{ FirefoxPlugins }}"

- name: Create Firefox profiles
  command: "firefox -CreateProfile {{ item }}"
  loop:
    - low_user1
    - low_user2
    - high_user1
    - high_user2

- name: Create policies.json for Firefox
  template:
    src: "policies.json.j2"
    dest: "/usr/lib/firefox/distribution/policies.json"
  become: true
  become_method: sudo




